export const INITIAL_QUERY_SEARCH_LIST = 'INITIAL_QUERY_SEARCH_LIST';
export const QUERY_SEARCH_LIST = 'QUERY_SEARCH_LIST';
export const SORT_SEARCH_LIST = 'SORT_SEARCH_LIST';
export const FILTER_SEARCH_LIST = 'FILTER_SEARCH_LIST';
export const PAGINATION_SEARCH_LIST = 'PAGINATION_SEARCH_LIST';
